module.exports = {
  extends: 'lighthouse:default',
  settings: {
    onlyCategories: ['performance', 'accessibility', 'best-practices', 'seo', 'pwa'],
    formFactor: 'mobile',
    screenEmulation: {
      mobile: true,
      width: 412,
      height: 823,
      deviceScaleFactor: 1.75,
      disabled: false,
    },
    emulatedUserAgent:
      'Mozilla/5.0 (Linux; Android 11; ONEPLUS A6013) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Mobile Safari/537.36',
    throttling: {
      rttMs: 150,
      throughputKbps: 1638.4,
      requestLatencyMs: 562.5,
      downloadThroughputKbps: 1638.4,
      uploadThroughputKbps: 819.2,
      cpuSlowdownMultiplier: 4,
    },
    skipAudits: [],
  },
  audits: [],
  categories: {
    performance: {
      title: 'Performance',
      description: 'These metrics show how your app performs for end users.',
      auditRefs: [
        { id: 'first-contentful-paint', weight: 10 },
        { id: 'largest-contentful-paint', weight: 25 },
        { id: 'cumulative-layout-shift', weight: 15 },
        { id: 'speed-index', weight: 10 },
        { id: 'interactive', weight: 15 },
        { id: 'first-input-delay', weight: 10 },
        { id: 'total-blocking-time', weight: 0 },
        { id: 'uses-responsive-images', weight: 0 },
        { id: 'offscreen-images', weight: 0 },
        { id: 'unminified-css', weight: 0 },
        { id: 'unminified-javascript', weight: 0 },
        { id: 'unused-css-rules', weight: 0 },
        { id: 'uses-text-compression', weight: 0 },
        { id: 'uses-optimized-images', weight: 0 },
        { id: 'modern-image-formats', weight: 0 },
      ],
    },
    accessibility: {
      title: 'Accessibility',
      description: 'These checks highlight opportunities to improve the accessibility of your web app.',
      auditRefs: [
        { id: 'aria-allowed-attr', weight: 1 },
        { id: 'aria-hidden-body', weight: 1 },
        { id: 'button-name', weight: 3 },
        { id: 'color-contrast', weight: 3 },
        { id: 'image-alt', weight: 3 },
        { id: 'label', weight: 3 },
      ],
    },
    'best-practices': {
      title: 'Best Practices',
      description: 'We recommend these checks to ensure your site meets modern web standards.',
      auditRefs: [
        { id: 'appcache-manifest', weight: 1 },
        { id: 'doctype', weight: 1 },
        { id: 'external-anchors-use-rel-noopener', weight: 1 },
        { id: 'geolocation-on-start', weight: 1 },
        { id: 'notification-on-start', weight: 1 },
        { id: 'password-inputs-can-be-pasted-into', weight: 1 },
      ],
    },
    seo: {
      title: 'SEO',
      description: 'Check your SEO performance.',
      auditRefs: [
        { id: 'canonical', weight: 1 },
        { id: 'crawlable-anchors', weight: 1 },
        { id: 'font-size', weight: 1 },
        { id: 'hreflang', weight: 1 },
        { id: 'html-has-lang', weight: 1 },
        { id: 'meta-description', weight: 1 },
      ],
    },
    pwa: {
      title: 'PWA',
      description: 'Check your Progressive Web App score.',
      auditRefs: [
        { id: 'installable-manifest', weight: 2 },
        { id: 'service-worker', weight: 1 },
        { id: 'splash-screen', weight: 1 },
        { id: 'themed-omnibox', weight: 1 },
      ],
    },
  },
};
