import { JourneyStage } from '@great-indian-wedding/theme-engine';
import {
  MockDb,
  MockDateVenue,
  MockVendor,
  MockDestination,
  MockFlight,
  MockHotel,
} from './types';

const now = new Date().toISOString();

export function buildSeedDb(): MockDb {
  return {
    currentUserId: null,
    users: {
      'user-priya': {
        id: 'user-priya',
        email: 'priya@example.com',
        displayName: 'Priya',
        coupleId: 'couple-priya-arjun',
        partnerId: 'user-arjun',
      },
      'user-arjun': {
        id: 'user-arjun',
        email: 'arjun@example.com',
        displayName: 'Arjun',
        coupleId: 'couple-priya-arjun',
        partnerId: 'user-priya',
      },
      'user-meera': {
        id: 'user-meera',
        email: 'meera@example.com',
        displayName: 'Meera',
        coupleId: 'couple-meera-rohan',
        partnerId: 'user-rohan',
      },
      'user-rohan': {
        id: 'user-rohan',
        email: 'rohan@example.com',
        displayName: 'Rohan',
        coupleId: 'couple-meera-rohan',
        partnerId: 'user-meera',
      },
    },
    profiles: {
      'user-priya': {
        userId: 'user-priya',
        firstName: 'Priya',
        lastName: 'Sharma',
        age: 27,
        city: 'Delhi',
        motherTongue: 'Hindi',
        religion: 'Hindu',
        profession: 'UX Designer',
        education: 'Masters in Design',
        diet: 'vegetarian',
        drinking: false,
        smoking: false,
        familyType: 'nuclear',
        kundaliType: 'CREATIVE_KARAN',
        gunaMilanScore: 28,
        bio: 'Designer who lives for monsoon chai, Kishore Kumar evenings, and unplanned Lodhi Garden walks.',
        emoji: '🌸',
        completed: true,
      },
      'user-arjun': {
        userId: 'user-arjun',
        firstName: 'Arjun',
        lastName: 'Mehta',
        age: 29,
        city: 'Delhi',
        motherTongue: 'Hindi',
        religion: 'Hindu',
        profession: 'Product Manager',
        education: 'MBA, IIM Bangalore',
        diet: 'non-vegetarian',
        drinking: true,
        smoking: false,
        familyType: 'joint',
        kundaliType: 'AMBITIOUS_ARJUN',
        gunaMilanScore: 30,
        bio: 'PM by day, jazz pianist by night. Looking for someone to argue about Tarantino vs. Anurag Kashyap with.',
        emoji: '🎹',
        completed: true,
      },
      'user-meera': {
        userId: 'user-meera',
        firstName: 'Meera',
        lastName: 'Iyer',
        age: 26,
        city: 'Mumbai',
        motherTongue: 'Tamil',
        religion: 'Hindu',
        profession: 'Doctor',
        education: 'MBBS, MD Pediatrics',
        diet: 'vegetarian',
        drinking: false,
        smoking: false,
        familyType: 'nuclear',
        kundaliType: 'NURTURING_NAINA',
        gunaMilanScore: 32,
        bio: 'Pediatrician who cries at every Pixar opening. Bharatanatyam dancer, terrible cook, excellent friend.',
        emoji: '💐',
        completed: true,
      },
      'user-rohan': {
        userId: 'user-rohan',
        firstName: 'Rohan',
        lastName: 'Kapoor',
        age: 30,
        city: 'Mumbai',
        motherTongue: 'Punjabi',
        religion: 'Sikh',
        profession: 'Architect',
        education: 'Bachelor of Architecture',
        diet: 'non-vegetarian',
        drinking: true,
        smoking: false,
        familyType: 'nuclear',
        kundaliType: 'STEADFAST_SAMEER',
        gunaMilanScore: 29,
        bio: 'Architect who sketches buildings on coffee shop napkins. Trekker, terrible singer, weekend potter.',
        emoji: '🏛️',
        completed: true,
      },
    },
    couples: {
      'couple-priya-arjun': {
        id: 'couple-priya-arjun',
        user1Id: 'user-priya',
        user2Id: 'user-arjun',
        coupleName: 'Priya & Arjun',
        journeyStage: JourneyStage.SEEKING,
        createdAt: now,
        updatedAt: now,
      },
      'couple-meera-rohan': {
        id: 'couple-meera-rohan',
        user1Id: 'user-meera',
        user2Id: 'user-rohan',
        coupleName: 'Meera & Rohan',
        journeyStage: JourneyStage.SEEKING,
        createdAt: now,
        updatedAt: now,
      },
    },
    matches: {
      'couple-priya-arjun': [
        {
          id: 'match-pa-1',
          forCoupleId: 'couple-priya-arjun',
          candidateName: 'Arjun Mehta',
          candidateAge: 29,
          candidateCity: 'Delhi',
          candidateProfession: 'Product Manager',
          candidateBio: 'PM by day, jazz pianist by night. Looking for someone to argue about Tarantino vs. Anurag Kashyap with.',
          emoji: '🎹',
          compatibilityScore: 91,
          gunaMilanScore: 30,
          status: 'pending',
        },
        {
          id: 'match-pa-2',
          forCoupleId: 'couple-priya-arjun',
          candidateName: 'Vikram Sethi',
          candidateAge: 31,
          candidateCity: 'Delhi',
          candidateProfession: 'Investment Banker',
          candidateBio: 'Numbers guy who still believes in love letters. Spends weekends restoring old motorcycles.',
          emoji: '🏍️',
          compatibilityScore: 74,
          gunaMilanScore: 22,
          status: 'pending',
        },
        {
          id: 'match-pa-3',
          forCoupleId: 'couple-priya-arjun',
          candidateName: 'Karan Bhatia',
          candidateAge: 28,
          candidateCity: 'Gurgaon',
          candidateProfession: 'Filmmaker',
          candidateBio: 'Indie filmmaker, vinyl collector, dog dad. Will quote Wong Kar-wai unprompted.',
          emoji: '🎬',
          compatibilityScore: 81,
          gunaMilanScore: 26,
          status: 'pending',
        },
      ],
      'couple-meera-rohan': [
        {
          id: 'match-mr-1',
          forCoupleId: 'couple-meera-rohan',
          candidateName: 'Rohan Kapoor',
          candidateAge: 30,
          candidateCity: 'Mumbai',
          candidateProfession: 'Architect',
          candidateBio: 'Architect who sketches buildings on coffee shop napkins. Trekker, terrible singer, weekend potter.',
          emoji: '🏛️',
          compatibilityScore: 88,
          gunaMilanScore: 29,
          status: 'pending',
        },
        {
          id: 'match-mr-2',
          forCoupleId: 'couple-meera-rohan',
          candidateName: 'Aditya Rao',
          candidateAge: 28,
          candidateCity: 'Mumbai',
          candidateProfession: 'Data Scientist',
          candidateBio: 'ML engineer who teaches kids to code on weekends. Marathoner, F1 nerd, mediocre guitarist.',
          emoji: '🏃',
          compatibilityScore: 77,
          gunaMilanScore: 24,
          status: 'pending',
        },
      ],
    },
    scheduledDates: {
      'couple-priya-arjun': null,
      'couple-meera-rohan': null,
    },
    weddings: {
      'couple-priya-arjun': null,
      'couple-meera-rohan': null,
    },
    vendorBookings: {
      'couple-priya-arjun': [],
      'couple-meera-rohan': [],
    },
    honeymoons: {
      'couple-priya-arjun': null,
      'couple-meera-rohan': null,
    },
    honeymoonBookings: {
      'couple-priya-arjun': [],
      'couple-meera-rohan': [],
    },
    timelines: {
      'couple-priya-arjun': [],
      'couple-meera-rohan': [],
    },
  };
}

export const SEED_VENUES: MockDateVenue[] = [
  {
    id: 'venue-cha-bar',
    name: 'Cha Bar at Oxford Bookstore',
    address: 'Connaught Place, Delhi',
    type: 'cafe',
    budgetEstimate: 600,
    dressCode: 'Casual',
    conversationStarters: [
      'Which book changed how you see the world?',
      'Tea or coffee — and the story behind it?',
      'What is one place that feels like home to you?',
      'Tell me about a Sunday that made you happy.',
      'Who taught you the most about love growing up?',
    ],
  },
  {
    id: 'venue-lodhi-garden',
    name: 'Lodhi Garden Sunset Walk',
    address: 'Lodhi Road, Delhi',
    type: 'garden',
    budgetEstimate: 200,
    dressCode: 'Comfortable',
    conversationStarters: [
      'What season do you feel most yourself in?',
      'Do you remember your first crush?',
      'What is the bravest thing you have ever done?',
      'If you had one extra hour every day, what would you do?',
      'Tell me about a friendship that changed your life.',
    ],
  },
  {
    id: 'venue-indian-accent',
    name: 'Indian Accent',
    address: 'The Lodhi, Delhi',
    type: 'restaurant',
    budgetEstimate: 4500,
    dressCode: 'Smart Casual',
    conversationStarters: [
      'What flavor reminds you of childhood?',
      'A meal you would love to share with me one day?',
      'Tell me about a city that made you feel alive.',
      'What is one risk you are glad you took?',
      'Where would you spend a perfect anniversary?',
    ],
  },
  {
    id: 'venue-humayuns-tomb',
    name: "Humayun's Tomb at Dusk",
    address: 'Nizamuddin, Delhi',
    type: 'heritage',
    budgetEstimate: 300,
    dressCode: 'Casual',
    conversationStarters: [
      'What is a story you carry from your grandparents?',
      'Have you ever felt time stop somewhere?',
      'What tradition do you want to keep alive?',
      'Tell me about an art form that moves you.',
      'Is there a place you keep returning to?',
    ],
  },
  {
    id: 'venue-marine-drive',
    name: 'Marine Drive Walk + Bhel',
    address: 'Marine Drive, Mumbai',
    type: 'heritage',
    budgetEstimate: 250,
    dressCode: 'Casual',
    conversationStarters: [
      'What does the sea remind you of?',
      'A Mumbai memory that defines you?',
      'Where do you go when you need to think?',
      'Tell me about a song that always finds you.',
      'What kind of love did you grow up watching?',
    ],
  },
  {
    id: 'venue-bandra-bandstand',
    name: 'Bandstand Promenade Cafe',
    address: 'Bandra, Mumbai',
    type: 'cafe',
    budgetEstimate: 800,
    dressCode: 'Casual',
    conversationStarters: [
      'What is your idea of a perfect Sunday morning?',
      'If you could only keep one playlist forever?',
      'Tell me about a small kindness you remember.',
      'Where do you see yourself in five rainy days?',
      'What makes a city feel like yours?',
    ],
  },
];

export const SEED_VENDORS: MockVendor[] = [
  {
    id: 'vendor-decor-1',
    name: 'Pushp Mandap Decorators',
    category: 'Decorator',
    city: 'Delhi',
    rating: 4.8,
    reviewCount: 312,
    priceRange: '₹2L – ₹6L',
    basePrice: 250000,
    description: 'Marigold-heavy traditional setups with modern fabric draping. Known for sangeet stages.',
    emoji: '🌼',
    verified: true,
  },
  {
    id: 'vendor-decor-2',
    name: 'Aurora Wedding Studio',
    category: 'Decorator',
    city: 'Mumbai',
    rating: 4.7,
    reviewCount: 218,
    priceRange: '₹3L – ₹10L',
    basePrice: 400000,
    description: 'Boutique decorators for beachside and rooftop weddings. Fairy-light specialists.',
    emoji: '✨',
    verified: true,
  },
  {
    id: 'vendor-cater-1',
    name: 'Bikaner Royal Caterers',
    category: 'Caterer',
    city: 'Delhi',
    rating: 4.9,
    reviewCount: 540,
    priceRange: '₹800/plate – ₹2500/plate',
    basePrice: 350000,
    description: 'Multi-cuisine catering with strong Rajasthani thali game. 500+ weddings catered.',
    emoji: '🍛',
    verified: true,
  },
  {
    id: 'vendor-cater-2',
    name: 'Saraswat Coastal Catering',
    category: 'Caterer',
    city: 'Mumbai',
    rating: 4.7,
    reviewCount: 191,
    priceRange: '₹1200/plate – ₹3000/plate',
    basePrice: 480000,
    description: 'Konkani, Mangalorean & Goan seafood-forward menus. Live counters their specialty.',
    emoji: '🦐',
    verified: true,
  },
  {
    id: 'vendor-photo-1',
    name: 'Reels of Forever',
    category: 'Photographer',
    city: 'Delhi',
    rating: 4.9,
    reviewCount: 287,
    priceRange: '₹1.5L – ₹5L',
    basePrice: 200000,
    description: 'Candid + cinematic teams. Two-day coverage with same-day edited reel.',
    emoji: '📸',
    verified: true,
  },
  {
    id: 'vendor-photo-2',
    name: 'Heirloom Lens Co.',
    category: 'Photographer',
    city: 'Mumbai',
    rating: 4.8,
    reviewCount: 156,
    priceRange: '₹2L – ₹7L',
    basePrice: 280000,
    description: 'Editorial-style wedding photography. Their albums look like Vogue spreads.',
    emoji: '🎞️',
    verified: true,
  },
  {
    id: 'vendor-mehendi-1',
    name: 'Veena Mehendi Atelier',
    category: 'Mehendi Artist',
    city: 'Delhi',
    rating: 4.9,
    reviewCount: 421,
    priceRange: '₹15K – ₹60K',
    basePrice: 25000,
    description: 'Bridal mehendi with detailed Rajasthani motifs. Team of 8 for guests.',
    emoji: '🌿',
    verified: true,
  },
  {
    id: 'vendor-music-1',
    name: 'Dhol Baaje Live',
    category: 'Musician/DJ',
    city: 'Delhi',
    rating: 4.6,
    reviewCount: 178,
    priceRange: '₹50K – ₹2L',
    basePrice: 80000,
    description: 'Live dhol team + sangeet DJ + sufi vocalists. Full evening package.',
    emoji: '🥁',
    verified: false,
  },
  {
    id: 'vendor-makeup-1',
    name: 'Sahiba Bridal Studio',
    category: 'Makeup Artist',
    city: 'Mumbai',
    rating: 4.9,
    reviewCount: 365,
    priceRange: '₹50K – ₹1.5L',
    basePrice: 65000,
    description: 'HD bridal makeup with airbrush. Specializes in dewy, no-cakey looks.',
    emoji: '💄',
    verified: true,
  },
];

export const SEED_DESTINATIONS: MockDestination[] = [
  {
    id: 'dest-maldives',
    name: 'Maldives',
    country: 'Maldives',
    archetype: 'Beach Lovers',
    description: 'Overwater bungalows, lagoons in 12 shades of blue, and nothing on your calendar.',
    whyPerfect: 'Zero visa friction, max privacy, and the kind of quiet that lets you actually talk again.',
    bestTimeToVisit: 'Nov – Mar',
    budgetMin: 350000,
    budgetMax: 900000,
    emoji: '🏝️',
    highlights: ['Overwater villa', 'Bioluminescent beach', 'Private sandbank picnic', 'Sunset dolphin cruise'],
  },
  {
    id: 'dest-bali',
    name: 'Bali',
    country: 'Indonesia',
    archetype: 'Beach Lovers',
    description: 'Rice terraces, jungle villas with private pools, sunset cocktails in Seminyak.',
    whyPerfect: 'A honeymoon that flexes from spiritual mornings in Ubud to wild nights at La Brisa.',
    bestTimeToVisit: 'Apr – Oct',
    budgetMin: 180000,
    budgetMax: 500000,
    emoji: '🌴',
    highlights: ['Tegallalang rice terraces', 'Uluwatu cliff sunset', 'Jungle villa stay', 'Couples spa'],
  },
  {
    id: 'dest-switzerland',
    name: 'Switzerland',
    country: 'Switzerland',
    archetype: 'Mountain Romantics',
    description: 'Alpine train rides, chocolate, and views you used to only see in old DDLJ posters.',
    whyPerfect: 'When you want every window to look unreal and every meal to feel earned.',
    bestTimeToVisit: 'Jun – Sep',
    budgetMin: 550000,
    budgetMax: 1500000,
    emoji: '🏔️',
    highlights: ['Jungfraujoch', 'Glacier Express', 'Interlaken paragliding', 'Lake Lucerne sunset'],
  },
  {
    id: 'dest-kashmir',
    name: 'Kashmir',
    country: 'India',
    archetype: 'Mountain Romantics',
    description: 'Shikara rides at dawn, snow on the Pir Panjal, kahwa by a wood stove.',
    whyPerfect: 'When you want the romance of Switzerland with the soul of home.',
    bestTimeToVisit: 'Apr – Sep',
    budgetMin: 90000,
    budgetMax: 300000,
    emoji: '⛰️',
    highlights: ['Dal Lake houseboat', 'Gulmarg gondola', 'Pahalgam pony ride', 'Mughal gardens'],
  },
  {
    id: 'dest-santorini',
    name: 'Santorini',
    country: 'Greece',
    archetype: 'Luxury Loungers',
    description: 'Cliff-side infinity pools, blue domes, and caldera sunsets you keep on your lock screen forever.',
    whyPerfect: 'The most photogenic honeymoon money can buy. And the wine is good too.',
    bestTimeToVisit: 'May – Sep',
    budgetMin: 500000,
    budgetMax: 1300000,
    emoji: '🌅',
    highlights: ['Oia sunset', 'Caldera catamaran', 'Volcanic beach', 'Wine tasting Megalochori'],
  },
  {
    id: 'dest-rajasthan',
    name: 'Udaipur',
    country: 'India',
    archetype: 'Culture Explorers',
    description: 'Lake palaces, royal corridors, mirror-tiled courtyards lit by hundreds of candles.',
    whyPerfect: 'For couples who want their first trip together to feel like a chapter in a novel.',
    bestTimeToVisit: 'Oct – Mar',
    budgetMin: 120000,
    budgetMax: 600000,
    emoji: '🏰',
    highlights: ['Taj Lake Palace stay', 'Pichola sunset boat', 'City Palace tour', 'Bagore-ki-Haveli show'],
  },
];

export const SEED_FLIGHTS: MockFlight[] = [
  {
    id: 'flight-dl-mle-1',
    airline: 'IndiGo',
    flightNumber: '6E 1471',
    from: 'Delhi',
    to: 'Male (Maldives)',
    departureTime: '02:55',
    durationMinutes: 285,
    price: 38400,
    stops: 0,
    class: 'economy',
  },
  {
    id: 'flight-dl-mle-2',
    airline: 'Vistara',
    flightNumber: 'UK 235',
    from: 'Delhi',
    to: 'Male (Maldives)',
    departureTime: '04:15',
    durationMinutes: 320,
    price: 82500,
    stops: 0,
    class: 'business',
  },
  {
    id: 'flight-bom-dps-1',
    airline: 'Singapore Airlines',
    flightNumber: 'SQ 423',
    from: 'Mumbai',
    to: 'Denpasar (Bali)',
    departureTime: '23:50',
    durationMinutes: 540,
    price: 46200,
    stops: 1,
    class: 'economy',
  },
  {
    id: 'flight-dl-zrh-1',
    airline: 'Swiss',
    flightNumber: 'LX 147',
    from: 'Delhi',
    to: 'Zurich',
    departureTime: '14:00',
    durationMinutes: 480,
    price: 72500,
    stops: 0,
    class: 'economy',
  },
  {
    id: 'flight-dl-srinagar',
    airline: 'IndiGo',
    flightNumber: '6E 2031',
    from: 'Delhi',
    to: 'Srinagar',
    departureTime: '07:30',
    durationMinutes: 90,
    price: 8400,
    stops: 0,
    class: 'economy',
  },
  {
    id: 'flight-bom-jfk',
    airline: 'Emirates',
    flightNumber: 'EK 502',
    from: 'Mumbai',
    to: 'Santorini (via Athens)',
    departureTime: '04:25',
    durationMinutes: 720,
    price: 88500,
    stops: 1,
    class: 'economy',
  },
  {
    id: 'flight-dl-udr',
    airline: 'Air India',
    flightNumber: 'AI 471',
    from: 'Delhi',
    to: 'Udaipur',
    departureTime: '11:10',
    durationMinutes: 75,
    price: 5400,
    stops: 0,
    class: 'economy',
  },
];

export const SEED_HOTELS: MockHotel[] = [
  {
    id: 'hotel-soneva',
    name: 'Soneva Fushi',
    city: 'Maldives',
    rating: 4.9,
    pricePerNight: 95000,
    amenities: ['Private pool', 'In-villa dining', 'Bicycle access', 'Outdoor cinema'],
    romanticFeatures: ['Floating breakfast', 'Stargazing observatory', 'Couples spa pavilion'],
    emoji: '🏝️',
  },
  {
    id: 'hotel-coco-collection',
    name: 'Coco Bodu Hithi',
    city: 'Maldives',
    rating: 4.8,
    pricePerNight: 62000,
    amenities: ['Overwater villa', 'House reef', 'All-inclusive', 'Sunset bar'],
    romanticFeatures: ['Sandbank picnic', 'Spa over the lagoon', 'Private dhoni cruise'],
    emoji: '🌊',
  },
  {
    id: 'hotel-mandapa',
    name: 'Mandapa, a Ritz-Carlton Reserve',
    city: 'Bali',
    rating: 4.9,
    pricePerNight: 75000,
    amenities: ['Riverside pool villa', 'Yoga shala', 'Library', 'Floating breakfast'],
    romanticFeatures: ['Couples Ayurvedic ritual', 'Private dinner at Sawah Terrace', 'Sunset paddle'],
    emoji: '🌿',
  },
  {
    id: 'hotel-bvlgari',
    name: 'Bulgari Resort Bali',
    city: 'Bali',
    rating: 4.9,
    pricePerNight: 105000,
    amenities: ['Cliffside villa', 'Private beach access', 'Italian dining', 'Couples spa'],
    romanticFeatures: ['Il Ristorante 8-course', 'Spa hammam ritual', 'Private cliffside dinner'],
    emoji: '✨',
  },
  {
    id: 'hotel-the-chedi-andermatt',
    name: 'The Chedi Andermatt',
    city: 'Switzerland',
    rating: 4.8,
    pricePerNight: 68000,
    amenities: ['Asian-Swiss fusion', 'Spa & saunas', 'Ski-in/ski-out', 'Cheese tower'],
    romanticFeatures: ['Private fondue dinner', 'Glacier helicopter tour', 'Indoor-outdoor pool'],
    emoji: '🏔️',
  },
  {
    id: 'hotel-houseboat-dal',
    name: 'Sukoon Houseboat',
    city: 'Kashmir',
    rating: 4.7,
    pricePerNight: 14500,
    amenities: ['Hand-carved walnut interiors', 'Shikara on call', 'Kashmiri kitchen'],
    romanticFeatures: ['Sunrise shikara breakfast', 'Wazwan dinner', 'Lake-facing veranda'],
    emoji: '🛶',
  },
  {
    id: 'hotel-canaves',
    name: 'Canaves Oia Suites',
    city: 'Santorini',
    rating: 4.9,
    pricePerNight: 78000,
    amenities: ['Caldera-view plunge pool', 'Cycladic suites', 'Wine cellar', 'Sea-view restaurant'],
    romanticFeatures: ['Sunset wine pairing', 'Catamaran day cruise', 'Private terrace dinner'],
    emoji: '🤍',
  },
  {
    id: 'hotel-taj-lake-palace',
    name: 'Taj Lake Palace',
    city: 'Udaipur',
    rating: 4.9,
    pricePerNight: 52000,
    amenities: ['Lake Pichola island palace', 'Royal butler', 'Spa boat', 'Heritage suites'],
    romanticFeatures: ['Jharokha dinner', 'Royal boat arrival', 'Private courtyard spa'],
    emoji: '👑',
  },
];
