import { DestinationCard, TravelerArchetype } from '../types';

export const HONEYMOON_DESTINATIONS: DestinationCard[] = [
  // Beach Lovers
  {
    id: 'maldives',
    name: 'Maldives',
    country: 'Maldives',
    archetype: TravelerArchetype.BEACH_LOVERS,
    description: 'Overwater bungalows, crystal clear waters, and pristine beaches',
    whyPerfect: 'Perfect for tropical paradise lovers with crystal-clear waters and exclusive island resorts',
    bestTimeToVisit: 'November to March',
    weatherAdvisory: 'Dry season, perfect weather, 25-30°C',
    estimatedBudget: { min: 300000, max: 1000000 },
    currency: 'MVR (Maldivian Rufiyaa)',
    visaRequirement: 'none',
    visaDetails: '30 days visa-free for Indian passport holders',
    culturalTips: [
      'Respect Islamic culture - dress modestly in public',
      'Island resorts have their own rules (more relaxed dress codes)',
      'Learn basic Dhivehi greetings',
    ],
    packingEssentials: [
      'Lightweight clothes',
      'Reef-safe sunscreen',
      'Snorkeling gear',
      'Underwaters camera',
    ],
    highlights: [
      'Snorkeling & scuba diving',
      'Water sports',
      'Sunset cruises',
      'Spa treatments',
      'Local island tours',
    ],
  },
  {
    id: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    archetype: TravelerArchetype.BEACH_LOVERS,
    description: 'Volcanic beaches, rice terraces, and vibrant culture',
    whyPerfect: 'Affordable tropical paradise with incredible food and spiritual experiences',
    bestTimeToVisit: 'April to October',
    weatherAdvisory: 'Dry season, 25-28°C, minimal rainfall',
    estimatedBudget: { min: 100000, max: 400000 },
    currency: 'IDR (Indonesian Rupiah)',
    visaRequirement: 'visa_on_arrival',
    visaDetails: '30-day visa on arrival (₹1000-2000)',
    culturalTips: [
      'Temples are sacred - dress respectfully',
      'Learn Balinese greetings',
      'Respect local customs during ceremonies',
    ],
    packingEssentials: ['Lightweight clothes', 'Sarongs', 'Temple attire', 'Reef-safe sunscreen'],
    highlights: [
      'Ubud rice terraces',
      'Tanah Lot temple',
      'Scuba diving',
      'Balinese massage',
      'Local markets',
    ],
  },
  {
    id: 'andaman',
    name: 'Andaman & Nicobar',
    country: 'India',
    archetype: TravelerArchetype.BEACH_LOVERS,
    description: 'Tropical islands with pristine beaches, coral reefs, and adventure',
    whyPerfect: 'India\'s own island paradise with no visa needed and incredible marine life',
    bestTimeToVisit: 'October to May',
    weatherAdvisory: 'Pleasant, 23-28°C, ideal for water sports',
    estimatedBudget: { min: 80000, max: 300000 },
    currency: 'INR',
    visaRequirement: 'none',
    visaDetails: 'No visa needed - Indian soil!',
    culturalTips: [
      'Respect local tribal communities',
      'Follow national park rules',
      'Be environmentally conscious',
    ],
    packingEssentials: ['Beach wear', 'Snorkeling gear', 'Waterproof bag', 'First aid kit'],
    highlights: [
      'Havelock Island',
      'Radhanagar Beach',
      'Scuba diving',
      'Cellular Jail visit',
      'Water sports',
    ],
  },

  // Mountain Romantics
  {
    id: 'kashmir',
    name: 'Kashmir',
    country: 'India',
    archetype: TravelerArchetype.MOUNTAIN_ROMANTICS,
    description: 'The "Paradise on Earth" with stunning mountains, lakes, and valleys',
    whyPerfect: 'Romantic mountain scenery, houseboats on Dal Lake, and Mughal gardens',
    bestTimeToVisit: 'April to September',
    weatherAdvisory: 'Cool, crisp air, 15-25°C, occasional rain',
    estimatedBudget: { min: 80000, max: 300000 },
    currency: 'INR',
    visaRequirement: 'none',
    visaDetails: 'No visa needed - Indian state',
    culturalTips: [
      'Respect local culture and traditions',
      'Learn Kashmiri words',
      'Be respectful at religious sites',
    ],
    packingEssentials: ['Light jackets', 'Comfortable shoes', 'Shawls', 'Camera'],
    highlights: [
      'Dal Lake shikara ride',
      'Gulmarg meadows',
      'Pahalgam valley',
      'Mughal gardens',
      'Local markets',
    ],
  },
  {
    id: 'switzerland',
    name: 'Switzerland',
    country: 'Switzerland',
    archetype: TravelerArchetype.MOUNTAIN_ROMANTICS,
    description: 'The Alps, Swiss villages, and fairy-tale landscapes',
    whyPerfect: 'Breathtaking mountain views, romantic train rides, and world-class hospitality',
    bestTimeToVisit: 'June to September',
    weatherAdvisory: 'Mild, 15-23°C, perfect hiking weather',
    estimatedBudget: { min: 500000, max: 1500000 },
    currency: 'CHF (Swiss Franc)',
    visaRequirement: 'advance_visa',
    visaDetails: 'Schengen visa required - apply 2-3 months in advance',
    culturalTips: [
      'Be punctual (Swiss are very time-conscious)',
      'Learn basic German/French greetings',
      'Respect nature and hiking trails',
    ],
    packingEssentials: ['Hiking boots', 'Layered clothing', 'Waterproof jacket', 'Camera'],
    highlights: [
      'Jungfrau Mountain',
      'Swiss Glacier Express',
      'Interlaken',
      'Zermatt',
      'Alpine hiking',
    ],
  },
  {
    id: 'bhutan',
    name: 'Bhutan',
    country: 'Bhutan',
    archetype: TravelerArchetype.MOUNTAIN_ROMANTICS,
    description: 'The land of the Thunder Dragon with pristine nature and spirituality',
    whyPerfect: 'Untouched Himalayan beauty, Buddhist monasteries, and sustainable tourism',
    bestTimeToVisit: 'April to June, September to November',
    weatherAdvisory: 'Cool, 10-20°C, clear skies',
    estimatedBudget: { min: 150000, max: 500000 },
    currency: 'BTN (Bhutanese Ngultrum)',
    visaRequirement: 'advance_visa',
    visaDetails: 'Visa arranged through authorized tour operator',
    culturalTips: [
      'Dress modestly',
      'Learn Buddhist customs',
      'Respect archery as national sport',
    ],
    packingEssentials: ['Warm clothing', 'Hiking boots', 'Layers', 'Respectful attire'],
    highlights: [
      'Tiger\'s Nest Monastery',
      'Punakha Dzong',
      'Hikes through valleys',
      'Traditional villages',
      'Buddhist culture',
    ],
  },

  // Culture Explorers
  {
    id: 'rajasthan',
    name: 'Rajasthan',
    country: 'India',
    archetype: TravelerArchetype.CULTURE_EXPLORERS,
    description: 'The land of kings with magnificent forts, palaces, and vibrant culture',
    whyPerfect: 'Rich Mughal history, golden deserts, and world-class heritage hotels',
    bestTimeToVisit: 'October to March',
    weatherAdvisory: 'Pleasant, 15-28°C, ideal weather',
    estimatedBudget: { min: 60000, max: 300000 },
    currency: 'INR',
    visaRequirement: 'none',
    visaDetails: 'No visa needed',
    culturalTips: [
      'Learn about Rajasthani history',
      'Respect local customs in villages',
      'Bargain in local markets',
    ],
    packingEssentials: ['Light clothes', 'Sunscreen', 'Scarf', 'Comfortable shoes'],
    highlights: [
      'Taj Mahal',
      'City Palace',
      'Hawa Mahal',
      'Desert safari',
      'Palace hotels',
    ],
  },
  {
    id: 'italy',
    name: 'Italy',
    country: 'Italy',
    archetype: TravelerArchetype.CULTURE_EXPLORERS,
    description: 'The birthplace of the Renaissance with art, history, and romance',
    whyPerfect: 'World-class museums, historic sites, and world-renowned cuisine',
    bestTimeToVisit: 'April to June, September to October',
    weatherAdvisory: 'Pleasant, 18-28°C, ideal for sightseeing',
    estimatedBudget: { min: 300000, max: 1000000 },
    currency: 'EUR (Euro)',
    visaRequirement: 'advance_visa',
    visaDetails: 'Schengen visa required - apply 2-3 months in advance',
    culturalTips: [
      'Learn Italian greetings',
      'Dress respectfully in churches',
      'Respect art and history',
    ],
    packingEssentials: ['Comfortable shoes', 'Casual smart clothes', 'Camera', 'Daypack'],
    highlights: [
      'Rome & Colosseum',
      'Venice canals',
      'Florence museums',
      'Tuscany countryside',
      'Italian cuisine',
    ],
  },

  // Adventure Seekers
  {
    id: 'iceland',
    name: 'Iceland',
    country: 'Iceland',
    archetype: TravelerArchetype.ADVENTURE_SEEKERS,
    description: 'Land of fire and ice with waterfalls, glaciers, and dramatic landscapes',
    whyPerfect: 'Unique adventure experiences, midnight sun, and otherworldly scenery',
    bestTimeToVisit: 'June to August',
    weatherAdvisory: 'Cool, 10-15°C, long daylight hours',
    estimatedBudget: { min: 400000, max: 1200000 },
    currency: 'ISK (Icelandic Króna)',
    visaRequirement: 'advance_visa',
    visaDetails: 'Schengen visa required',
    culturalTips: [
      'Respect geothermal areas',
      'Follow safety rules for hiking',
      'Dress warmly despite summer season',
    ],
    packingEssentials: [
      'Waterproof jacket',
      'Hiking boots',
      'Layers',
      'Swimwear',
      'Warm hat',
    ],
    highlights: [
      'Golden Circle',
      'Glacier hiking',
      'Waterfall chasing',
      'Blue Lagoon',
      'Northern lights (winter)',
    ],
  },
  {
    id: 'ladakh',
    name: 'Ladakh',
    country: 'India',
    archetype: TravelerArchetype.ADVENTURE_SEEKERS,
    description: 'The "Land of the Gods" with high-altitude deserts and Buddhist culture',
    whyPerfect: 'Ultimate adventure destination with trekking, biking, and pristine nature',
    bestTimeToVisit: 'June to September',
    weatherAdvisory: 'Cool, 8-20°C, altitude 3000m+',
    estimatedBudget: { min: 80000, max: 300000 },
    currency: 'INR',
    visaRequirement: 'none',
    visaDetails: 'No visa needed',
    culturalTips: [
      'Acclimatize to altitude',
      'Respect Buddhist monasteries',
      'Learn about local culture',
    ],
    packingEssentials: [
      'High SPF sunscreen',
      'Warm clothing',
      'Trekking shoes',
      'Altitude medicine',
    ],
    highlights: [
      'Pangong Lake',
      'Khardung La pass',
      'Monasteries',
      'Lamayuru',
      'Trekking & biking',
    ],
  },

  // Luxury Loungers
  {
    id: 'dubai',
    name: 'Dubai',
    country: 'UAE',
    archetype: TravelerArchetype.LUXURY_LOUNGERS,
    description: 'Ultra-modern luxury with world-class shopping, dining, and hospitality',
    whyPerfect: 'Luxury resorts, designer shopping, fine dining, and desert experiences',
    bestTimeToVisit: 'October to April',
    weatherAdvisory: 'Pleasant, 20-28°C, very little rain',
    estimatedBudget: { min: 300000, max: 1000000 },
    currency: 'AED (UAE Dirham)',
    visaRequirement: 'e_visa',
    visaDetails: 'E-visa available online for 30 days',
    culturalTips: [
      'Respect Islamic culture',
      'Dress modestly in public areas',
      'Learn about local customs',
    ],
    packingEssentials: ['Light clothes', 'Sunscreen', 'Swimwear', 'Modest evening wear'],
    highlights: [
      'Burj Khalifa',
      'Palm Jumeirah',
      'Desert safari',
      'Luxury shopping',
      'Spa treatments',
    ],
  },
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    archetype: TravelerArchetype.LUXURY_LOUNGERS,
    description: 'The City of Light - romance, art, fashion, and exquisite dining',
    whyPerfect: 'Ultimate romantic destination with luxury hotels, fine dining, and timeless beauty',
    bestTimeToVisit: 'April to June, September to October',
    weatherAdvisory: 'Mild, 12-20°C, ideal weather',
    estimatedBudget: { min: 400000, max: 1500000 },
    currency: 'EUR',
    visaRequirement: 'advance_visa',
    visaDetails: 'Schengen visa required - apply 2-3 months in advance',
    culturalTips: [
      'Learn French greetings',
      'Dress smartly for dinners',
      'Respect local customs',
    ],
    packingEssentials: [
      'Smart casual clothes',
      'Comfortable walking shoes',
      'Light jacket',
      'Camera',
    ],
    highlights: [
      'Eiffel Tower',
      'Louvre Museum',
      'Seine River cruise',
      'Michelin restaurants',
      'Champs-Élysées',
    ],
  },
];

export function getDestinationsByArchetype(archetype: TravelerArchetype): DestinationCard[] {
  return HONEYMOON_DESTINATIONS.filter((d) => d.archetype === archetype);
}

export function getDestinationById(id: string): DestinationCard | undefined {
  return HONEYMOON_DESTINATIONS.find((d) => d.id === id);
}

export function getRandomDestinations(count: number = 3): DestinationCard[] {
  const shuffled = [...HONEYMOON_DESTINATIONS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
